/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  FilterBought: { // input type
    bought: boolean; // Boolean!
  }
  ItemInput: { // input type
    description: string; // String!
    name: string; // String!
    price: number; // Float!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Item: { // root type
    bought: boolean; // Boolean!
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    price: number; // Float!
  }
  ItemId: { // root type
    id: string; // ID!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Item: { // field return type
    bought: boolean; // Boolean!
    description: string; // String!
    id: string; // ID!
    name: string; // String!
    price: number; // Float!
  }
  ItemId: { // field return type
    id: string; // ID!
  }
  Mutation: { // field return type
    addItem: NexusGenRootTypes['Item']; // Item!
    deleteItem: NexusGenRootTypes['ItemId']; // ItemId!
    markBought: NexusGenRootTypes['ItemId']; // ItemId!
  }
  Query: { // field return type
    item: NexusGenRootTypes['Item'] | null; // Item
    items: NexusGenRootTypes['Item'][]; // [Item!]!
  }
}

export interface NexusGenFieldTypeNames {
  Item: { // field return type name
    bought: 'Boolean'
    description: 'String'
    id: 'ID'
    name: 'String'
    price: 'Float'
  }
  ItemId: { // field return type name
    id: 'ID'
  }
  Mutation: { // field return type name
    addItem: 'Item'
    deleteItem: 'ItemId'
    markBought: 'ItemId'
  }
  Query: { // field return type name
    item: 'Item'
    items: 'Item'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addItem: { // args
      item: NexusGenInputs['ItemInput']; // ItemInput!
    }
    deleteItem: { // args
      id: string; // ID!
    }
    markBought: { // args
      id: string; // ID!
    }
  }
  Query: {
    item: { // args
      id: string; // ID!
    }
    items: { // args
      filterBought?: NexusGenInputs['FilterBought'] | null; // FilterBought
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}